In [64]:
import pandas as pd

In [65]:
# Read data from the given .csv file
df = pd.read_csv('po2_data.csv', header = 0)
df.iloc[:,0:11]

,subject#,age,sex,test_time,motor_updrs,total_updrs,jitter(%),jitter(abs),jitter(rap),jitter(ppq5),jitter(ddp)
0,1,72,0,5.6431,28.199,34.398,0.00662,0.000034,0.00401,0.00317,0.01204
1,1,72,0,12.6660,28.447,34.894,0.00300,0.000017,0.00132,0.00150,0.00395
2,1,72,0,19.6810,28.695,35.389,0.00481,0.000025,0.00205,0.00208,0.00616
3,1,72,0,25.6470,28.905,35.810,0.00528,0.000027,0.00191,0.00264,0.00573
4,1,72,0,33.6420,29.187,36.375,0.00335,0.000020,0.00093,0.00130,0.00278
...,...,...,...,...,...,...,...,...,...,...,...
5870,42,61,0,142.7900,22.485,33.485,0.00406,0.000031,0.00167,0.00168,0.00500
5871,42,61,0,149.8400,21.988,32.988,0.00297,0.000025,0.00119,0.00147,0.00358
5872,42,61,0,156.8200,21.495,32.495,0.00349,0.000025,0.00152,0.00187,0.00456
5873,42,61,0,163.7300,21.007,32.007,0.00281,0.000020,0.00128,0.00151,0.00383
5874,42,61,0,170.7300,20.513,31.513,0.00282,0.000021,0.00135,0.00166,0.00406

In [66]:
df.iloc[:,11:22]

,shimmer(%),shimmer(abs),shimmer(apq3),shimmer(apq5),shimmer(apq11),shimmer(dda),nhr,hnr,rpde,dfa,ppe
0,0.02565,0.230,0.01438,0.01309,0.01662,0.04314,0.014290,21.640,0.41888,0.54842,0.16006
1,0.02024,0.179,0.00994,0.01072,0.01689,0.02982,0.011112,27.183,0.43493,0.56477,0.10810
2,0.01675,0.181,0.00734,0.00844,0.01458,0.02202,0.020220,23.047,0.46222,0.54405,0.21014
3,0.02309,0.327,0.01106,0.01265,0.01963,0.03317,0.027837,24.445,0.48730,0.57794,0.33277
4,0.01703,0.176,0.00679,0.00929,0.01819,0.02036,0.011625,26.126,0.47188,0.56122,0.19361
...,...,...,...,...,...,...,...,...,...,...,...
5870,0.01896,0.160,0.00973,0.01133,0.01549,0.02920,0.025137,22.369,0.64215,0.55314,0.21367
5871,0.02315,0.215,0.01052,0.01277,0.01904,0.03157,0.011927,22.886,0.52598,0.56518,0.12621
5872,0.02499,0.244,0.01371,0.01456,0.01877,0.04112,0.017701,25.065,0.47792,0.57888,0.14157
5873,0.01484,0.131,0.00693,0.00870,0.01307,0.02078,0.007984,24.422,0.56865,0.56327,0.14204
5874,0.01907,0.171,0.00946,0.01154,0.01470,0.02839,0.008172,23.259,0.58608,0.57077,0.15336

In [67]:
# Check the shape of the data set
df.shape

(5875, 22)

## Data cleaning

In [68]:
# Check if there's any missing values or abnormal data
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5875 entries, 0 to 5874
Data columns (total 22 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   subject#        5875 non-null   int64
 1   age             5875 non-null   int64
 2   sex             5875 non-null   int64
 3   test_time       5875 non-null   float64
 4   motor_updrs     5875 non-null   float64
 5   total_updrs     5875 non-null   float64
 6   jitter(%)       5875 non-null   float64
 7   jitter(abs)     5875 non-null   float64
 8   jitter(rap)     5875 non-null   float64
 9   jitter(ppq5)    5875 non-null   float64
 10  jitter(ddp)     5875 non-null   float64
 11  shimmer(%)      5875 non-null   float64
 12  shimmer(abs)    5875 non-null   float64
 13  shimmer(apq3)   5875 non-null   float64
 14  shimmer(apq5)   5875 non-null   float64
 15  shimmer(apq11)  5875 non-null   float64
 16  shimmer(dda)    5875 non-null   float64
 17  nhr             5875 non-null   float64
 18  hnr             5875 non-null   float64
 19  rpde            5875 non-null   float64
 20  dfa             5875 non-null   float64
 21  ppe             5875 non-null   float64
dtypes: float64(19), int64(3)
memory usage: 1009.9 KB

In [69]:
# Check if there's any null value
df.isnull()

,subject#,age,sex,test_time,motor_updrs,total_updrs,jitter(%),jitter(abs),jitter(rap),jitter(ppq5),...,shimmer(abs),shimmer(apq3),shimmer(apq5),shimmer(apq11),shimmer(dda),nhr,hnr,rpde,dfa,ppe
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5870,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
5871,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
5872,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
5873,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
5874,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [70]:
df.isnull().sum()

subject#          0
age               0
sex               0
test_time         0
motor_updrs       0
total_updrs       0
jitter(%)         0
jitter(abs)       0
jitter(rap)       0
jitter(ppq5)      0
jitter(ddp)       0
shimmer(%)        0
shimmer(abs)      0
shimmer(apq3)     0
shimmer(apq5)     0
shimmer(apq11)    0
shimmer(dda)      0
nhr               0
hnr               0
rpde              0
dfa               0
ppe               0
dtype: int64

In [71]:
df[df.isnull().any(axis=1)]

Empty DataFrame
Columns: [subject#, age, sex, test_time, motor_updrs, total_updrs, jitter(%), jitter(abs), jitter(rap), jitter(ppq5), jitter(ddp), shimmer(%), shimmer(abs), shimmer(apq3), shimmer(apq5), shimmer(apq11), shimmer(dda), nhr, hnr, rpde, dfa, ppe]
Index: []

[0 rows x 22 columns]

=> There is no null value in the dataset

## Feature engineering

### New variables

##### jitter-shimmer-difference ratio = Jitter(d.d.p) / Shimmer(d.d.a)

Both Jitter and Shimmer are pivotal for voice quality. So, we choose "jitter_shimmer_difference_ratio" because it combines variations between consecutive voice cycles, providing a comprehensive assessment of voice stability and instability, particularly vital in distinguishing Parkinson's symptoms.

AZADI, H., AKBARZADEH-T, M.-R., SHOEIBI, A. & KOBRAVI, H. R. 2021. Evaluating the Effect of Parkinson's Disease on Jitter and Shimmer Speech Features. Advanced biomedical research [Online], 10. Available: http://europepmc.org/abstract/MED/35127581
https://doi.org/10.4103/abr.abr_254_21
https://europepmc.org/articles/PMC8781904
https://europepmc.org/articles/PMC8781904?pdf=render [Accessed 2021].

In [72]:
jitter_shimmer_difference_ratio = df.loc[:, 'jitter(ddp)'] / df.loc[:, 'shimmer(dda)']
jitter_shimmer_difference_ratio_df = pd.DataFrame(jitter_shimmer_difference_ratio, columns=['jitter_shimmer_difference_ratio'])
jitter_shimmer_difference_ratio_df

      jitter_shimmer_difference_ratio
0                            0.279091
1                            0.132461
2                            0.279746
3                            0.172746
4                            0.136542
...                               ...
5870                         0.171233
5871                         0.113399
5872                         0.110895
5873                         0.184312
5874                         0.143008

[5875 rows x 1 columns]

#####  Harmonicity Difference = hnrâˆ’ nhr

The difference between the Harmonic-to-Noise ratio (HNR) and Noise-to-Harmonic ratio (NHR) can give insights into the balance of noise and harmonics in the voice. A larger difference might indicate better voice quality, while a smaller difference may indicate disturbances, potentially correlating with disease severity.

BENBA, A., JILBAB, A. & HAMMOUCH, A. 2016. Voice analysis for detecting patients with Parkinson's disease using the hybridization of the best acoustic features. International Journal on Electrical Engineering and Informatics, 8, 108.

FERRAND, C. T. 2002. Harmonics-to-noise ratio: an index of vocal aging. Journal of voice, 16, 480-487.

In [73]:
harmonicity_difference = df.loc[:,'hnr'] - df.loc[:,'nhr']
harmonicity_difference_df = pd.DataFrame(harmonicity_difference, columns=['harmonicity_difference'])
harmonicity_difference_df

      harmonicity_difference
0                  21.625710
1                  27.171888
2                  23.026780
3                  24.417163
4                  26.114375
...                      ...
5870               22.343863
5871               22.874073
5872               25.047299
5873               24.414016
5874               23.250828

[5875 rows x 1 columns]

### Add new variables to make a new dataset

In [74]:
# Combine the new variables with the old data to create a single dataset, getting it ready for analysis.
new_df = pd.concat((df, jitter_shimmer_difference_ratio_df, harmonicity_difference_df,), axis=1, ignore_index=False)
new_df

,subject#,age,sex,test_time,motor_updrs,total_updrs,jitter(%),jitter(abs),jitter(rap),jitter(ppq5),...,shimmer(apq5),shimmer(apq11),shimmer(dda),nhr,hnr,rpde,dfa,ppe,jitter_shimmer_difference_ratio,harmonicity_difference
0,1,72,0,5.6431,28.199,34.398,0.00662,0.000034,0.00401,0.00317,...,0.01309,0.01662,0.04314,0.014290,21.640,0.41888,0.54842,0.16006,0.279091,21.625710
1,1,72,0,12.6660,28.447,34.894,0.00300,0.000017,0.00132,0.00150,...,0.01072,0.01689,0.02982,0.011112,27.183,0.43493,0.56477,0.10810,0.132461,27.171888
2,1,72,0,19.6810,28.695,35.389,0.00481,0.000025,0.00205,0.00208,...,0.00844,0.01458,0.02202,0.020220,23.047,0.46222,0.54405,0.21014,0.279746,23.026780
3,1,72,0,25.6470,28.905,35.810,0.00528,0.000027,0.00191,0.00264,...,0.01265,0.01963,0.03317,0.027837,24.445,0.48730,0.57794,0.33277,0.172746,24.417163
4,1,72,0,33.6420,29.187,36.375,0.00335,0.000020,0.00093,0.00130,...,0.00929,0.01819,0.02036,0.011625,26.126,0.47188,0.56122,0.19361,0.136542,26.114375
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5870,42,61,0,142.7900,22.485,33.485,0.00406,0.000031,0.00167,0.00168,...,0.01133,0.01549,0.02920,0.025137,22.369,0.64215,0.55314,0.21367,0.171233,22.343863
5871,42,61,0,149.8400,21.988,32.988,0.00297,0.000025,0.00119,0.00147,...,0.01277,0.01904,0.03157,0.011927,22.886,0.52598,0.56518,0.12621,0.113399,22.874073
5872,42,61,0,156.8200,21.495,32.495,0.00349,0.000025,0.00152,0.00187,...,0.01456,0.01877,0.04112,0.017701,25.065,0.47792,0.57888,0.14157,0.110895,25.047299
5873,42,61,0,163.7300,21.007,32.007,0.00281,0.000020,0.00128,0.00151,...,0.00870,0.01307,0.02078,0.007984,24.422,0.56865,0.56327,0.14204,0.184312,24.414016
5874,42,61,0,170.7300,20.513,31.513,0.00282,0.000021,0.00135,0.00166,...,0.01154,0.01470,0.02839,0.008172,23.259,0.58608,0.57077,0.15336,0.143008,23.250828

In [76]:
# Save the new data to a new .csv file
new_df.to_csv('new_po2_data.csv', index=False, header=True)